Fiap.Exemplo01.MVC.Web/Models/Cliente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Fiap.Exemplo01.MVC.Web.Models
{
    public class Cliente
    {
        public string nome { get; set; }
        public int idade { get; set; }
        public decimal credito { get; set; }

        [Display(Name = "Possui necessidades especiais?")]
        public bool NecessidadesEspeciais { get; set; }

       [Display(Name = "Estado Civil")]
        public string EstadoCivil {get; set;}

        [Display(Name = "Data de Nascimento")]
        public DateTime DataNascimento { get; set; }

    }
}

Fiap.Exemplo01.MVC.Web/Models/Produto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fiap.Exemplo01.MVC.Web.Models
{
    public class Produto
    {
        public string Nome { get; set; }
        public int Quantidade { get; set; }
        public decimal Valor { get; set; }

    }
}

Fiap.Exemplo01.MVC.Web/Controllers/ClienteController.cs
using Fiap.Exemplo01.MVC.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap.Exemplo01.MVC.Web.Controllers
{
    public class ClienteController : Controller
    {
        // GET: Cliente
        [HttpGet]
        public ActionResult Cadastrar()
        {
            var lista = new List<string>();
            lista.Add("Solteiro");
            lista.Add("Casado");
            lista.Add("Separado");

            ViewBag.estados = new SelectList(lista);

            return View();
        }

        private static List<Cliente> _lista = new List<Cliente>();
        [HttpPost]
        public ActionResult Cadastrar(Cliente cliente)
        {
            _lista.Add(cliente);
            TempData["msg"] = "Cliente Cadastrado!";
            return RedirectToAction("Cadastrar"); // rsolve o problema de na hora de salvar o cadastro, f5 cadastra tudo em branco.


        }

        public ActionResult Listar()
        {
            ViewBag.lista = _lista;
            return View();
        }
    }
}

Fiap.Exemplo01.MVC.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap.Exemplo01.MVC.Web.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }

    }
}

Fiap.Exemplo01.MVC.Web/Controllers/ProdutoController.cs
using Fiap.Exemplo01.MVC.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fiap.Exemplo01.MVC.Web.Controllers
{
    public class ProdutoController : Controller
    {
        private static List<Produto> _lista = new List<Produto>();

        [HttpGet]
        public ActionResult Listar()
        {
            return View(_lista);
        }

        [HttpGet] // Carrega a pagina com o formulário
        public ActionResult Cadastrar()
        {
            return View(); //<- // botao direito aqui, pra criar uma view já no lugar certo
        }

        [HttpPost]
        // mvca tab tab 

        //get abre pagina

        //post processa info

        public ActionResult Cadastrar(Produto produto)
        {
            // viewbag.nome que vc quiser (cria na hora) 

            // é como se fosse um variavel global // 
            _lista.Add(produto);
            ViewBag.prod = produto;


            TempData["mensagem"] = "Produto Cadastrado!";

            //Retorna a view Sucesso.cshtml.
            //colocar o ,produto é para o 3ºjeito de enviar as informações para outra view.
            return View("Sucesso",produto);

            //return Content(produto.Nome + " " + produto.Valor + " " + produto.Quantidade);
        }
    }
}

Fiap.Exemplo01.MVC.Web/Views/Cliente/Cadastrar.cshtml
@model Fiap.Exemplo01.MVC.Web.Models.Cliente
@{
    ViewBag.Title = "Cadastrar";
}

<h2>.:Cadastrar Cliente:.</h2>
@Helper.Message(TempData["msg"] as string)


@using (Html.BeginForm())
{
    <div class="form-group">
        @Html.LabelFor(c => c.nome)
        @Html.TextBoxFor(c => c.nome, new { placeholder = "Digite seu nome", @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(c => c.idade)
        @Html.TextBoxFor(c => c.idade,new { @class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(c => c.credito)
        @Html.TextBoxFor(c => c.credito, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Html.LabelFor(c => c.NecessidadesEspeciais)
        @Html.CheckBoxFor(c => c.NecessidadesEspeciais)
    </div>
    <div class="form-group">
        @Html.LabelFor(c => c.EstadoCivil)
        @Html.DropDownListFor(c => c.EstadoCivil,ViewBag.estados as SelectList,new {@class = "form-control" })
    </div>
    <div class="form-group">
        @Html.LabelFor(c => c.DataNascimento)
        @Html.TextBoxFor(c => c.DataNascimento, new { @class = "form-control" })
    </div>

    <div class="form-group">
        @Helper.Submit("Salvar","btn btn-primary")
    </div>

    @section scripts
    {
        <!-- <script></script> -->
    }
}

Fiap.Exemplo01.MVC.Web/Views/Cliente/Listar.cshtml
@{
    ViewBag.Title = "Listar";
}

<h2>Listar</h2>


<table class="table-bordered">
    <tr>
        <th style="padding:10px">Nome Do Cliente<br></th>
        <th style="padding:10px">Idade do Cliente<br></th>
        <th style="padding:10px">Crédito do Cliente<br></th>
        <th style="padding:10px">Estado Civil<br></th>
    </tr>
@foreach (var client in ViewBag.lista)
{
    <tr>
        <td>@client.nome</td>
        <td>@client.idade</td>
        <td>@client.credito</td>
        <td>@client.EstadoCivil</td>
     </tr>
}
</table>

Fiap.Exemplo01.MVC.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<h2>Index</h2>

Fiap.Exemplo01.MVC.Web/Views/Produto/Cadastrar.cshtml
@{
    ViewBag.Title = "Cadastrar";
}

<h2>Cadastrar</h2>

<!-- Nome,Valor Quantidade-->

<form method="post" action="/Produto/Cadastrar">
    <div class="form-group">
        <p>
            <label>
                Digite o nome do produto:
                <input type="text" name="nome" class="form-control"/>
            </label>
        </p>
    </div>
    <div class="form-group">
        <p>
            <label>
                Digite o valor do produto:
                <input type="text" name="valor" class="form-control" />
            </label>
        </p>
    </div>
    <div class="form-group">
        <p>
            <label>
                Digite a quantidade do produto:
                <input type="text" name="quantidade" class="form-control"/>
            </label>
        </p>
    </div>

        <p>
            <input type="submit" value="Enviar" class="btn btn-primary" />
        </p>


</form>

Fiap.Exemplo01.MVC.Web/Views/Produto/Listar.cshtml
@model List<Fiap.Exemplo01.MVC.Web.Models.Produto>

@{
    ViewBag.Title = "Listar";
}

<h2>.:Listar:.</h2>

<table class="table">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Quantidade</th>
            <th>Valor</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var produto in Model)
        {
            <tr>
                <td>@produto.Nome</td>
                <td> @produto.Quantidade</td>
                <td>@produto.Valor</td>
            </tr>
        }
    </tbody>
</table>

Fiap.Exemplo01.MVC.Web/Views/Produto/Sucesso.cshtml
@model Fiap.Exemplo01.MVC.Web.Models.Produto

@{
    ViewBag.Title = "Sucesso";
}

<h2>Sucesso</h2>

<h3>
   @Model.Nome
   @Model.Valor
   @Model.Quantidade
</h3>

<div class="alert alert-success">
    @TempData["mensagem"]
</div>

<p>
    Nome: @ViewBag.prod.Nome, Valor: @ViewBag.prod.Valor - @ViewBag.prod.Quantidade
</p>

Fiap.Exemplo01.MVC.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    @*<link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />*@
    <link href="~/Content/bootstraptheme.min.css" rel="stylesheet" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Cadastro de Produtos","Cadastrar","Produto")</li>
                    <li>@Html.ActionLink("Cadastro de Clientes", "Cadastrar", "Cliente")</li>
                    <li>@Html.ActionLink("Produtos", "Listar", "Produto")</li>
                    <li>@Html.ActionLink("Clientes", "Listar", "Cliente")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("scripts",false)

</body>
</html>